version: '3.8'
services:
  angular-app:
    image: eyajomli/angular:latest
    ports:
      - "4201:80"  # Specify ports as strings
    restart: always  # Restart should be under the service

  prometheus:
    image: prom/prometheus
    ports:
      - "3002:9002"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "4000:4010"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
  db:
